[workspace]
members = [
    "pexels-api",
    "pexels-cli",
]

resolver = "2"

[profile.release]
opt-level = 3

[workspace.package]
version = "0.0.1"
authors = ["https://github.com/houseme"]
edition = "2021"
rust-version = "1.80.0"
license = "MIT OR Apache-2.0"
description = "A Rust client for the Pexels API"
homepage = "https://github.com/houseme/pexels"
repository = "https://github.com/houseme/pexels.git"
documentation = "https://docs.rs/pexels"
readme = "./README.md"
keywords = ["pexels", "api", "client", "cli", "pexels-api"]
categories = ["web-programming", "development-tools", "Asynchronous", "network-programming"]

[workspace.dependencies]
clap = { version = "4.5.23", features = ["derive"] }
dotenv = "0.15.0"
pexels-api = { path = "pexels-api" }
reqwest = { version = "0.12.11", features = ["json"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
thiserror = "2.0.9 "
tokio = { version = "1", features = ["full"] }
url = "2.5.4"

