on:
  push:
    branches:
      - main

name: Docs

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5.0.0
        with:
          submodules: 'recursive'

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake libclang-dev

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Run cargo doc
        run: cargo doc --no-deps --all-features